# Generated by Django 5.0.3 on 2024-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congresses", "0009_congress_support_email_congress_support_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portrait",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "Sehr klein (XS)"),
                    ("S", "Klein (S)"),
                    ("M", "Mittel (M)"),
                    ("L", "Groß (L)"),
                    ("XL", "Sehr groß (XL)"),
                    ("2XL", "Extra groß (2XL)"),
                ],
                max_length=3,
                verbose_name="Konfektionsgröße",
            ),
        ),
    ]
