# Generated by Django 5.0.3 on 2024-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_is_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(help_text='Verwende <a target="_blank" href="https://www.markdownguide.org/cheat-sheet/">Markdown</a> zur Formatierung.', verbose_name='Beschreibung'),
        ),
    ]
