# Generated by Django 5.0.3 on 2024-03-30 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congresses', '0010_alter_portrait_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('desc', models.TextField(verbose_name='Beschreibung')),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresses.congress')),
            ],
            options={
                'verbose_name': 'Exkursion',
                'verbose_name_plural': 'Exkursionen',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.excursion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresses.participant')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['excursion', 'participant', '-priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='excursion',
            constraint=models.UniqueConstraint(fields=('congress', 'title'), name='unique_excursion'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('excursion', 'participant', 'priority'), name='unique_order'),
        ),
    ]
