# Generated by Django 5.0.3 on 2024-03-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresses', '0010_alter_portrait_size'),
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('excursion', 'participant'), name='unique_order'),
        ),
    ]
