# Generated by Django 5.0.3 on 2024-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_remove_order_unique_order_order_unique_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='desc',
            field=models.TextField(help_text='Verwende <a target="_blank" href="https://www.markdownguide.org/cheat-sheet/">Markdown</a> zur Formatierung.', verbose_name='Beschreibung'),
        ),
    ]
