# Generated by Django 5.0.3 on 2024-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_alter_excursion_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='url',
            field=models.URLField(blank=True, verbose_name='Webadresse'),
        ),
    ]
